### PR TITLE
Grid detector changes

### PR DESCRIPTION
**Pull request by jhardenberg**
Suggested changes to the grid-detector branch #33 . Includes a new test dataset with two variables on different grids and 3 vertical levels.

### CODE REVIEW

**Comment by oloapinivad** [comment]
I gave it a further look, and actually what was happening - at least on my local machine - was that the tempfile was not written correctly. I added a `load()` in the `_prepare_grid()` and now the weights generation works as expected even if we have two grids. @jhardenberg please let me know if works for you too. It would be cool to better handle tempfiles, since this seems to be related to #9

**Comment by jhardenberg** [comment]
Even with your `load()` it is still lcoking up when writing to the tempfile for me on lumi

**Comment by oloapinivad** [comment]
I assume there is something we are not doing fully right with `tempfiles`. 

Could you test the same command but without loading the data into memory but simply executing the Regridder from the file on the disk? 

```python
import xarray as xr
from smmregrid import Regridder
regridder = Regridder(source_grid="tests/data/ua-so_mix_ecearth.nc", target_grid="r180x90", method="bil", loglevel="debug")
```

if this works, it would confirm it is a problem with tempfiles. 


BTW, quite incredibily, this seems to work on my local machine! It is the first example of multiple horizontal grid support!!!!

```python
from smmregrid import Regridder
import xarray as xr
import os
indir='tests/data'
filename = os.path.join(indir, 'ua-so_mix_ecearth.nc')
data = xr.open_dataset(filename)
regrid = Regridder(data, 'r180x90', loglevel='debug')
regridded = regrid.regrid(data)
```

I visually inspected the output and seems all good! I am going to write an extra test for this multi grid case!

**Comment by jhardenberg** [comment]
The first example works for me on lumi

**Comment by jhardenberg** [comment]
and the second one too

**Comment by jhardenberg** [comment]
The lockup is in `_cdo_generate_weight()` ... I fear that there is an inconsistency between using dask and then trying to use parallel `Process` ....

**Comment by oloapinivad** [comment]
In the meanwhile I added a new test and fixed a small inconsistency in the way regrid is operated.

At this stage, this means that we can regrid multi grid if we start from grids. However, it is impossible to do this if we start from weights and we need to have a raise for this case

**Pull request merged**
