### PR TITLE
healpix support and test, error handling if dimension missing

### PR DESCRIPTION
**Pull request by oloapinivad**
This pull request includes a couple of tests for the interpolation of healpix and a small fixer to handle exceptions when dimensions are not the ones expected. The latter has to be improved...

### CODE REVIEW

**Comment by oloapinivad** [comment]
Last commit includes the possibility of specifying the spatial dimensions for interpolation. It also activates the previously disabled opportunity of generating the weights, and specying method for interpolation. the new predefined option is conservative remapping.

**Comment by oloapinivad** [comment]
@jhardenberg shall we merge?

**Comment by jhardenberg** [comment]
> @jhardenberg shall we merge?

Looks all good to me and I tested it. I could not test it in my setup using healpix data because of a separate data reading issue, but I see that you are testing on healpix data in the tests so that should be good.
So yes, for me let's merge!

**Comment by oloapinivad** [comment]
Great, merging!

**Pull request merged**
